#first we print the list of students
puts "The students of Villains Academt"
puts "-------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The JOker"
puts "Joffrey Baratheon"
puts "Norman Bates"
print "Overall, we have "
print 11
puts " great students"
